### ISSUE TITLE
More info

### ISSUE THREAD

**Issue by ewerlopes** [syedshabihhasan/TestE4#1]
Hi man!

I am now doing some research using the E4 band. So, I am looking for ways on how to get the data from the bad and used it on linux (in real time). Would you know if I can emulate the application on linux?

Thanks.

**Comment by syedshabihhasan** [comment]
Hi!

I am not aware of how one would achieve that. There are two possible ways in order of increasing difficulty, off the top of my head : 
1. You can try to contact the empatica folks and ask them if they can provide you with the API.
2. You can create a hack with the android emulator and a ble dongle to communicate with the bands.

If I were you, I would use option 1, and if it fails, think of a better way than option 2, and if that fails use option 2.

Cheers!
--Shabih
